'use strict';
const {app,BrowserWindow}=require('electron');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
fs.mkdirSync('artifacts',{recursive:true});
const profile=fs.mkdtempSync(path.join(os.tmpdir(),'peercast-smoke-'));app.setPath('userData',profile);
const results=[];const errors=[];let mainWindow;
const check=(value,name)=>{if(!value)throw Error(name);results.push({test:name,status:'PASS'});};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
app.on('browser-window-created',(_,window)=>{if(!mainWindow)mainWindow=window;window.webContents.on('console-message',(_,level,message)=>{if(level===3)errors.push(message);});});
require('../desktop/main.cjs');
(async()=>{
 await app.whenReady();await wait(1200);const w=mainWindow;const run=code=>w.webContents.executeJavaScript(code,true);
 check(!!w,'desktop window created');check(await run("!!document.querySelector('a[href=\"host.html\"]')"),'Home has Host entry');
 await w.loadFile(path.resolve('settings.html'));await wait(200);
 const initial=await run('peerCastDesktop.getSettings()');check(initial.startup===false,'startup defaults OFF');
 await run("(async()=>{await settingsReady;UI('resolution').value='1080';UI('fps').value='60';UI('saveSettings').click();})()");await wait(250);
 const stored=await run('peerCastDesktop.getSettings()');check(stored.resolution==='1080'&&stored.fps===60,'desktop settings persist atomically');
 await w.reload();await wait(350);check(await run("UI('fps').value==='60'"),'settings survive reload');
 await w.loadFile(path.resolve('host.html'));await wait(800);
 check(await run("UI('fps').value==='60' && !!peerCastDesktop"),'Host uses saved quality and restricted bridge');
 await w.webContents.capturePage().then(image=>fs.writeFileSync('artifacts/desktop-host.png',image.toPNG())).catch(error=>console.warn('Optional screenshot unavailable: '+error.message));
 const capability=await run('peerCastDesktop.capabilities()');check(capability.supported,'native capability IPC');
 check(Array.isArray(await run('peerCastDesktop.listAudioApplications()')),'native audio enumeration IPC');
 check((await run('peerCastDesktop.sources()')).length>0,'desktop display/window enumeration');
 check(await run("typeof require==='undefined'&&typeof process==='undefined'"),'renderer has no Node access');
 const hostile=await run("peerCastDesktop.startApplicationCapture(-1,'x').then(()=>false,()=>true)");check(hostile,'invalid capture PID rejected');
 await w.loadFile(path.resolve('viewer.html'));await wait(250);check(await run("peerCastDesktop.listAudioApplications().then(()=>false,()=>true)"),'Viewer cannot invoke Host native capture APIs');
 check(await run("typeof RTCPeerConnection==='function'&&typeof navigator.mediaDevices.getUserMedia==='function'"),'desktop WebRTC and media APIs available');
 await w.webContents.capturePage().then(image=>fs.writeFileSync('artifacts/desktop-viewer.png',image.toPNG())).catch(error=>console.warn('Optional screenshot unavailable: '+error.message));
 await w.loadFile(path.resolve('about.html'));await wait(100);check(await run("document.body.textContent.includes('0.2.0')"),'About product version');
 check(!errors.some(message=>/ReferenceError|TypeError|SyntaxError|Unable to load preload/.test(message)),'no desktop runtime/preload exceptions');
 fs.writeFileSync('artifacts/desktop-smoke.json',JSON.stringify({ok:true,results,console:errors},null,2));console.log(JSON.stringify({ok:true,results}));app.quit();
})().catch(error=>{console.error(error);fs.writeFileSync('artifacts/desktop-smoke.json',JSON.stringify({ok:false,error:error.stack,results,console:errors},null,2));app.exit(1);});
setTimeout(()=>{console.error('desktop smoke timeout');app.exit(1);},25000).unref();
