'use strict';
const {spawn,execFileSync}=require('node:child_process');const path=require('node:path');const fs=require('node:fs');
fs.mkdirSync('artifacts',{recursive:true});
const helper=path.resolve('native/PeerCast.Audio/bin/Release/net8.0/win-x64/publish/PeerCast.Audio.exe');
const wait=ms=>new Promise(r=>setTimeout(r,ms));const children=[];const results=[];
async function tone(frequency){const child=spawn('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',path.resolve('tests/tone.ps1'),'-Frequency',String(frequency)],{windowsHide:true,stdio:['pipe','pipe','pipe']});children.push(child);await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('tone timeout')),10000);child.stdout.once('data',()=>{clearTimeout(t);resolve();});child.on('error',reject);});return child;}
function energy(pcm,hz){let real=0,imag=0;const n=pcm.length/4;for(let i=0;i<n;i++){const value=pcm.readInt16LE(i*4)/32768;real+=value*Math.cos(2*Math.PI*hz*i/48000);imag+=value*Math.sin(2*Math.PI*hz*i/48000);}return Math.hypot(real,imag)/n;}
async function capture(process){const apps=JSON.parse(execFileSync(helper,['--list'],{encoding:'utf8',windowsHide:true}));const app=apps.find(a=>a.pid===process.pid);if(!app)throw Error('tone audio session missing');const child=spawn(helper,['--capture',String(app.pid),app.identity],{windowsHide:true,stdio:['pipe','pipe','pipe']});children.push(child);let status='';child.stderr.on('data',d=>status+=d);const chunks=[];let length=0;child.stdout.on('data',d=>{if(length<768000){chunks.push(d);length+=d.length;}});await wait(2500);child.stdin.end('stop\n');await Promise.race([new Promise(r=>child.once('exit',r)),wait(2000).then(()=>child.kill())]);if(length<48000)throw Error('insufficient PCM '+status);return {pcm:Buffer.concat(chunks),status};}
(async()=>{const a=await tone(440),b=await tone(880);await wait(600);const first=await capture(a);const e440=energy(first.pcm,440),e880=energy(first.pcm,880);if(!(e440>.001&&e440>e880*10))throw Error(`isolation failed 440=${e440} 880=${e880}`);results.push({test:'include process A excludes simultaneous process B',status:'PASS',energy440:e440,energy880:e880});const second=await capture(b);const b440=energy(second.pcm,440),b880=energy(second.pcm,880);if(!(b880>.001&&b880>b440*10))throw Error('reverse isolation failed');results.push({test:'include process B excludes simultaneous process A',status:'PASS',energy440:b440,energy880:b880});console.log(JSON.stringify({ok:true,results}));fs.writeFileSync('artifacts/native-result.json',JSON.stringify({ok:true,results},null,2));})().catch(error=>{console.error(error);process.exitCode=1;fs.writeFileSync('artifacts/native-result.json',JSON.stringify({ok:false,error:error.message,results},null,2));}).finally(()=>{for(const child of children){if(child.exitCode===null){child.stdin.end('\n');setTimeout(()=>child.kill(),1000).unref();}}});
