'use strict';
const {app}=require('electron');const fs=require('node:fs'),os=require('node:os'),path=require('node:path');app.setPath('userData',fs.mkdtempSync(path.join(os.tmpdir(),'pc-net-capture-')));let window;app.on('browser-window-created',(_,w)=>{if(!window)window=w;});require('../desktop/main.cjs');
fs.mkdirSync('artifacts',{recursive:true});
const report={};const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{await app.whenReady();await wait(500);await window.loadFile(path.resolve('host.html'));const run=code=>window.webContents.executeJavaScript(code,true);
 report.stun=await run(`(async()=>{const canvas=document.createElement('canvas');canvas.width=320;canvas.height=180;canvas.getContext('2d').fillRect(0,0,320,180);const stream=canvas.captureStream(30);const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});const types=new Set();pc.onicecandidate=e=>{if(e.candidate)types.add(e.candidate.type);};pc.addTrack(stream.getVideoTracks()[0],stream);await pc.setLocalDescription(await pc.createOffer());await new Promise(resolve=>{const timer=setTimeout(resolve,15000);pc.onicegatheringstatechange=()=>{if(pc.iceGatheringState==='complete'){clearTimeout(timer);resolve();}};});const result={gathering:pc.iceGatheringState,types:[...types],srflx:types.has('srflx')};pc.close();stream.getTracks().forEach(t=>t.stop());return result;})()`);
 await run("document.title='PeerCast automated capture surface'");await wait(300);
 report.capture=await run(`(async()=>{const sources=await peerCastDesktop.sources();const source=sources.find(s=>s.name==='PeerCast automated capture surface');if(!source)return {status:'NEEDS MANUAL TEST',reason:'test window not enumerated'};await peerCastDesktop.chooseSource(source.id,false);const stream=await navigator.mediaDevices.getDisplayMedia({video:{width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:60,max:60}},audio:false});const track=stream.getVideoTracks()[0];const settings=track.getSettings();stream.getTracks().forEach(t=>t.stop());return {status:'PASS',settings};})()`).catch(error=>({status:'FAILED',error:error.message}));
 fs.writeFileSync('artifacts/network-capture.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));app.quit();})().catch(error=>{console.error(error);app.exit(1);});setTimeout(()=>app.exit(2),40000).unref();
